# Generated by Django 5.1.3 on 2025-01-13 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csvs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geojson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_geojson', models.FileField(null=True, upload_to='state_geojson/')),
                ('district_geojson', models.FileField(null=True, upload_to='district_geojsons/')),
                ('sub_district_geojson', models.FileField(null=True, upload_to='sub_district_geojson/')),
                ('block_geojson', models.FileField(null=True, upload_to='block_geojson/')),
                ('pincode_geojson', models.FileField(null=True, upload_to='pincode_geojson/')),
                ('gram_panchayat_geojson', models.FileField(null=True, upload_to='gram_panchayat_geojson/')),
                ('town_village_geojson', models.FileField(null=True, upload_to='town_village_geojson/')),
            ],
        ),
        migrations.CreateModel(
            name='ColorRangeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('color_range_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='population.colorrangefamily')),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100, null=True)),
                ('sub_district', models.CharField(max_length=100, null=True)),
                ('block', models.CharField(max_length=100, null=True)),
                ('town_village', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('gram_panchayat', models.CharField(max_length=100, null=True)),
                ('population', models.IntegerField()),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='population.csv')),
            ],
        ),
    ]
