# Generated by Django 5.1.3 on 2025-01-14 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorrange',
            name='color_range_family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_ranges', to='population.colorrangefamily'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='block_geojson',
            field=models.FileField(null=True, upload_to='4block_geojson/'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='district_geojson',
            field=models.FileField(null=True, upload_to='2district_geojsons/'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='gram_panchayat_geojson',
            field=models.FileField(null=True, upload_to='6gram_panchayat_geojson/'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='pincode_geojson',
            field=models.FileField(null=True, upload_to='5pincode_geojson/'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='state_geojson',
            field=models.FileField(null=True, upload_to='1state_geojson/'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='sub_district_geojson',
            field=models.FileField(null=True, upload_to='3sub_district_geojson/'),
        ),
        migrations.AlterField(
            model_name='geojson',
            name='town_village_geojson',
            field=models.FileField(null=True, upload_to='7town_village_geojson/'),
        ),
    ]
